site_name: Tempo
site_url: https://tempo-organization.github.io/tempo-cli/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - content.tabs.link
  icon:
    logo: fontawesome/solid/t
    repo: fontawesome/brands/github
  palette:
    # Auto toggle for the user to switch between modes based on system preference
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

    # Default Dark Mode (for users who have dark mode preference)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: cyan

    # Default Light Mode (for users who have light mode preference)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: cyan


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            show_object_full_path: false
            members: true
            docstring_style: google
            separate_signature: true
            show_labels: false
nav:
  - Home: index.md
  - Introduction:
      - getting_started.md
      - help.md
  - Tutorials:
            - tutorials/index.md
            - Workflows:
                    - tutorials/workflows/index.md
                    - tutorials/workflows/standard.md
  - Reference:
            - reference/index.md
            - Commands:
                    - reference/commands/index.md
                    - clean: reference/commands/clean.md
                    - collection: reference/commands/collection.md
                    - dlc: reference/commands/dlc.md
                    - dump: reference/commands/dump.md
                    - file-io: reference/commands/file_io.md
                    - ini: reference/commands/ini.md
                    - init: reference/commands/init.md
                    - json: reference/commands/json.md
                    - mod: reference/commands/mod.md
                    - run: reference/commands/run.md
                    - toml: reference/commands/toml.md
                    - tool:
                        - install: reference/commands/tool/install.md
                    - uplugin: reference/commands/uplugin.md
                    - uproject: reference/commands/uproject.md
            - Config:
                    - reference/config/index.md
            - Environment Variables:
                    - reference/environment_variables/index.md
            - API:
                    - reference/api/index.md
  - FAQ: faq.md
  - Roadmap: to_do_list.md
  - Community: community.md

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/Tempo-Organization/tempo-cli
repo_name: tempo

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Tempo-Organization/tempo-cli
      name: Tempo on Github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/EvUuAD4QvS
      name: Tempo Discord Server

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - mkdocs-click
